backend = "etcd"
confdir = "/etc/confd"
log-level = "debug"
interval = 300
nodes = [
  "http://192.168.190.147:2379",
  "http://192.168.190.148:2379",
  "http://192.168.190.149:2379",
]
watch = true
noop = false
scheme = "http"
