backend = "etcdv3"
confdir = "/etc/confd"
log-level = "debug"
interval = 30
nodes = [
  "http://10.135.4.66:2379",
  "http://10.135.4.67:2379",
  "http://10.135.4.68:2379",
]
basic_auth = true
username = "root"
password = "passw0rd"
noop = false
scheme = "http"
